### ISSUE TITLE
Don't understand subpaths?

### ISSUE THREAD

**Issue by thejase** [mozilla-neutrino/react-router-starter#11]
Forgive my novice understanding, but I tried to change the route path for `AsyncBar` to:
```
<Route path="/bar/free" component={AsyncBar} />
```

Trying to go to it directly from the address bar yields an empty page with some errors:
![image](https://user-images.githubusercontent.com/787276/29999929-a8736d12-900e-11e7-9801-808a19492be4.png)

If I change it back to `path="/bar"`, I can hit it directly from the URL.

Am I just not understanding something about React Router?

**Comment by helfi92** [comment]
Hey @thejase , this issue was previously mentioned [here](https://github.com/mozilla-neutrino/neutrino-dev/issues/133). Hopefully this will help make you understand what's going on. For a quick fix, you can modify the publicPath in `.neutrinorc` to set the public path to `/`.

In `.neutrinorc`, change

```
module.exports = {
  use: [
    'neutrino-preset-react',
    neutrino => neutrino.config
      .entry('vendor')
        .add('react')
        .add('react-dom')
        .add('react-hot-loader')
        .add('react-router-dom')
        .add('react-async-component')
  ]
};

```
to: 
```
module.exports = {
  use: [
    'neutrino-preset-react',
    neutrino => neutrino.config
      .entry('vendor')
        .add('react')
        .add('react-dom')
        .add('react-hot-loader')
        .add('react-router-dom')
        .add('react-async-component')
        .end()
      .output.publicPath('/')
  ]
};
```

To interact with webpack configuration, neutrino uses (webpack-chain)[https://github.com/mozilla-neutrino/webpack-chain]. Hope that helps.

**Comment by thejase** [comment]
Thanks so much, especially for the patience as the neutrinos pass through this noggin'.

☮️
